name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları klonla
        uses: actions/checkout@v2

      - name: Java kur
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Gradle yetkilerini ver
        run: chmod +x ./gradlew

      - name: APK derle
        run: ./gradlew assembleDebug

      - name: APK dosyasını kaydet
        uses: actions/upload-artifact@v4
        with:
          name: uygulama-apk
          path: app/build/outputs/apk/debug/app-debug.apk
